# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run SwiftLint"
  lane :linter do
    swiftlint(
      config_file: ".swiftlint.yml",
      ignore_exit_status: true,
      raise_if_swiftlint_error: true,
      executable: "Pods/SwiftLint/swiftlint"
    )
  end

  desc "Build for testing"
  lane :build_for_testing do
    scan(
      workspace: "SurveyApp.xcworkspace",
      scheme: "SurveyApp Staging",
      derived_data_path: "derivedData",
      build_for_testing: true
    )
  end

  desc "Run unit test"
  lane :unit_test do
    scan(
      workspace: "SurveyApp.xcworkspace",
      scheme: "SurveyApp Staging",
      only_testing: ["SurveyAppTests"],
      derived_data_path: "derivedData",
      test_without_building: true
    )
  end

  desc "Run UI test"
  lane :ui_test do
    scan(
      workspace: "SurveyApp.xcworkspace",
      scheme: "SurveyApp Staging",
      only_testing: ["SurveyAppUITests"],
      derived_data_path: "derivedData",
      test_without_building: true,
      devices: ["iPhone 12"]
    )
  end

  desc "Upload to firebase app distribution"
  lane :upload_to_firebase do
    build_app(
      workspace: "SurveyApp.xcworkspace",
      scheme: "SurveyApp Staging",
      silent: true,
      configuration: "Staging",
      export_options: {
        method: "development"
      }
    )
    
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      groups: "testers",
      release_notes: "Release staging",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN']
    )
  end
end
